#!/bin/bash

# Set to a destination folder to copy files to
DEST="${HOME}/transfers/wm"

make clean
make
[ $? -eq 0 ] && {
  [ -x trim_lslo ] && {
    echo "Trimming comments from optimized LSL script"
    ./trim_lslo
  }
}

[ "$1" == "-c" ] && {
  rm -rf ${DEST}
  mkdir -p ${DEST}

  if [ "$2" == "-d" ]; then
    cp Controller.lsl ${DEST}/Controller.lsl
    cp Emitter.lsl ${DEST}/Emitter.lsl
  else
    cp Controller.lslo ${DEST}/Controller.lsl
    cp Emitter.lslo ${DEST}/Emitter.lsl
  fi
  cp COPYRIGHT LICENSE ${DEST}
  cp README.txt ${DEST}/README
}
